language: node_js

os:
  - linux

install:
  - npm install

node_js:
  - "6.2.1"
  - "5.0"

before_script:
  - npm run update -- --travis --token $GH_TOKEN
  - npm run demo-init -- --travis

script:
  - npm run build -- --travis
  - npm test

cache:
  directories:
  - node_modules

env:
  - GH_TOKEN=GH_TOKEN